/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChartsDthree {
        "data": string;
        "height": number;
        "width": number;
    }
    interface MyComponent {
    }
    interface StencilButton {
    }
    interface StencilHint {
        "msg": any;
        "psw": boolean;
    }
    interface StencilLabel {
        "label": any;
    }
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
declare global {
    interface HTMLChartsDthreeElement extends Components.ChartsDthree, HTMLStencilElement {
    }
    var HTMLChartsDthreeElement: {
        prototype: HTMLChartsDthreeElement;
        new (): HTMLChartsDthreeElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilButtonElement extends Components.StencilButton, HTMLStencilElement {
    }
    var HTMLStencilButtonElement: {
        prototype: HTMLStencilButtonElement;
        new (): HTMLStencilButtonElement;
    };
    interface HTMLStencilHintElement extends Components.StencilHint, HTMLStencilElement {
    }
    var HTMLStencilHintElement: {
        prototype: HTMLStencilHintElement;
        new (): HTMLStencilHintElement;
    };
    interface HTMLStencilLabelElement extends Components.StencilLabel, HTMLStencilElement {
    }
    var HTMLStencilLabelElement: {
        prototype: HTMLStencilLabelElement;
        new (): HTMLStencilLabelElement;
    };
    interface HTMLElementTagNameMap {
        "charts-dthree": HTMLChartsDthreeElement;
        "my-component": HTMLMyComponentElement;
        "stencil-button": HTMLStencilButtonElement;
        "stencil-hint": HTMLStencilHintElement;
        "stencil-label": HTMLStencilLabelElement;
    }
}
declare namespace LocalJSX {
    interface ChartsDthree {
        "data"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface MyComponent {
        "onSubmitLogin"?: (event: MyComponentCustomEvent<any>) => void;
    }
    interface StencilButton {
    }
    interface StencilHint {
        "msg"?: any;
        "psw"?: boolean;
    }
    interface StencilLabel {
        "label"?: any;
    }
    interface IntrinsicElements {
        "charts-dthree": ChartsDthree;
        "my-component": MyComponent;
        "stencil-button": StencilButton;
        "stencil-hint": StencilHint;
        "stencil-label": StencilLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "charts-dthree": LocalJSX.ChartsDthree & JSXBase.HTMLAttributes<HTMLChartsDthreeElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-button": LocalJSX.StencilButton & JSXBase.HTMLAttributes<HTMLStencilButtonElement>;
            "stencil-hint": LocalJSX.StencilHint & JSXBase.HTMLAttributes<HTMLStencilHintElement>;
            "stencil-label": LocalJSX.StencilLabel & JSXBase.HTMLAttributes<HTMLStencilLabelElement>;
        }
    }
}
